version: '3.8'

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - db
        entrypoint: ["sh", "-c", "npm run migrate:dev && npm run server:run"]
        networks:
            - app-network

    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        networks:
            - app-network

volumes:
    postgres:

networks:
    app-network:
        driver: bridge
