version: '3.8'

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - docker.env
        depends_on:
            - db
        entrypoint: ["sh", "-c", "npm run migrate:dev && npm run server:run"]
        networks:
            - app-network

    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        networks:
            - app-network

    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - ./nginx:/etc/nginx/conf.d/
        ports:
            - "443:443"
            - "80:80"
        networks:
            - app-network

volumes:
    postgres:

networks:
    app-network:
        driver: bridge
